RIG_NAME: __example_rig
MAIN_SYNC: True
device_bpod:
  COM_BPOD: null
  BPOD_TTL_TEST_DATE: null  # optional
  BPOD_TTL_TEST_STATUS: null  # optional
  SOUND_BOARD_BPOD_PORT: null  # optional
  ROTARY_ENCODER_BPOD_PORT: null  # optional
device_frame2ttl:
  COM_F2TTL: null
  F2TTL_CALIBRATION_DATE: 2099-12-31
  F2TTL_DARK_THRESH: 91.0
  F2TTL_LIGHT_THRESH: 51.0
device_rotary_encoder:
  COM_ROTARY_ENCODER: null
device_screen:
  DISPLAY_IDX: 1
  SCREEN_FREQ_TARGET: 60
  SCREEN_FREQ_TEST_DATE: null  # optional
  SCREEN_FREQ_TEST_STATUS: null  # optional
  SCREEN_LUX_DATE: null  # optional
  SCREEN_LUX_VALUE: null  # optional
device_sound:
  OUTPUT: sysdefault  # harp, hifi, xonar or sysdefault
  COM_SOUND: null
  ATTENUATION_DB: 0
device_microphone:
  BONSAI_WORKFLOW: devices/microphone/record_mic.bonsai
device_valve:
  WATER_CALIBRATION_DATE: 2099-12-31
  WATER_CALIBRATION_OPEN_TIMES: [50, 100]
  WATER_CALIBRATION_RANGE: [40, 140]
  WATER_CALIBRATION_WEIGHT_PERDROP: [1.25, 2.75]
  FREE_REWARD_VOLUME_UL: 1.5
device_cameras:  # remove the whole section if no camera is used on the rig
  left:
    BONSAI_WORKFLOW: devices/camera_recordings/TrainingRig_SaveVideo_TrainingTasks.bonsai
VERSION: 1.0.0
