name: iblrigv8 CI

on:
  push:
    branches: [iblrigv8]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [iblrigv8]
    paths-ignore:
      - 'docs/**'

jobs:
  tests:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.10"]
    steps:
      - name: Checkout iblrig repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: flake8
        run: |
          pip install --upgrade pip
          pip install flake8 --quiet
          python -m flake8

      - name: install requirements
        shell: bash -l {0}
        run: |
          pip install --editable .[DEV]

      - name: Checkout project extraction repo
        uses: actions/checkout@v4
        with:
          repository: int-brain-lab/project_extraction
          path: int-brain-lab

      - name: install requirements
        shell: bash -l {0}
        run: |
          pip install -e ./int-brain-lab/project_extraction

      - name: Install audio library (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libportaudio2

      - name: Create config files (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cp settings/hardware_settings_template.yaml settings/hardware_settings.yaml
          cp settings/iblrig_settings_template.yaml settings/iblrig_settings.yaml

      - name: Create config files (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          copy settings\hardware_settings_template.yaml settings\hardware_settings.yaml
          copy settings\iblrig_settings_template.yaml settings\iblrig_settings.yaml

      - name: iblrig unit tests
        run: |
          coverage run -m unittest discover -s ./iblrig/test -t .
          coverage xml

      - name: coveralls.io
        uses: coverallsapp/github-action@v2
        with:
          flag-name: ${{ matrix.python-version }}, ${{ matrix.os }}
          parallel: true
          file: coverage.xml
          compare-ref: iblrigv8

      - name: Generate requirements_frozen.txt
        run: pip freeze > requirements_frozen.txt

      - name: Store frozen requirements as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: requirements_frozen
          path: requirements_frozen.txt

  finish:
    needs: tests
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
