name: Release

on:
  workflow_dispatch:
  push:
#    tags:
#      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
          python-version-file: pyproject.toml
      - name: Install requirements
        run: pdm sync -dG doc
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          pre-build-command: "apt update -y && apt install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
          build-command: "pdm run make latexpdf"
      - uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/build/latex/iblrig.pdf
          retention-days: 1
