name: Release

on:
  workflow_dispatch:
  push:
#    tags:
#      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
          python-version-file: pyproject.toml
      - name: Install requirements
        run: pdm sync -dG doc
      - name: Sphinx build
        run: pdm run make -C docs/ simplepdf
      - uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/build/simplepdf/*.pdf
          retention-days: 1
