name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: Install requirements
        run: pdm sync -dG doc
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
          version: 1.0
      - name: Build PDF
        run: make -C docs/ latexpdf
      - uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/build/latex/iblrig.pdf
          retention-days: 1
